# Generated by Django 3.0.5 on 2020-04-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_load_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='the name of this status', max_length=50, verbose_name='Name')),
                ('send_email', models.BooleanField(default=True, help_text='if an email should be sent when a load changes to this status', verbose_name='Send Email')),
                ('order', models.IntegerField(blank=True, help_text='where this status should be displayed on a list of statuses', null=True, verbose_name='Display Order')),
                ('default_new', models.BooleanField(default=False, help_text='if this is the default for new loads (note:only one delivery status should be set to true)', verbose_name='Default for New')),
            ],
            options={
                'verbose_name': 'delivery satus',
                'verbose_name_plural': 'delivery statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='the name of this status', max_length=50, verbose_name='Name')),
                ('send_email', models.BooleanField(default=True, help_text='if an email should be sent when a load changes to this status', verbose_name='Send Email')),
                ('order', models.IntegerField(blank=True, help_text='where this status should be displayed on a list of statuses', null=True, verbose_name='Display Order')),
                ('default_new', models.BooleanField(default=False, help_text='if this is the default for new loads (note:only one installation status should be set to true)', verbose_name='Default for New')),
            ],
            options={
                'verbose_name': 'installation satus',
                'verbose_name_plural': 'installation statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='the name of this status', max_length=50, verbose_name='Name')),
                ('send_email', models.BooleanField(default=True, help_text='if an email should be sent when a load changes to this status', verbose_name='Send Email')),
                ('order', models.IntegerField(blank=True, help_text='where this status should be displayed on a list of statuses', null=True, verbose_name='Display Order')),
                ('default_new', models.BooleanField(default=False, help_text='if this is the default for new loads (note:only one receipt status should be set to true)', verbose_name='Default for New')),
            ],
            options={
                'verbose_name': 'receipt status',
                'verbose_name_plural': 'receipt statuses',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_status',
            field=models.ForeignKey(blank=True, help_text='the delivery status of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.DeliveryStatus', verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='load',
            name='installation_status',
            field=models.ForeignKey(blank=True, help_text='the installation status of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.InstallationStatus', verbose_name='Installation Status'),
        ),
        migrations.AddField(
            model_name='load',
            name='receipt_status',
            field=models.ForeignKey(blank=True, help_text='the receipt status of this load', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.ReceiptStatus', verbose_name='Receipt Status'),
        ),
    ]
