# Generated by Django 3.0.5 on 2020-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0005_auto_20200427_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='photo',
            field=models.URLField(blank=True, help_text='A link to a photo', verbose_name='Photo'),
        ),
    ]
