# Generated by Django 3.0.5 on 2020-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0006_load_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.ManyToManyField(help_text='the status of this load', to='loads.Status'),
        ),
    ]
