# Generated by Django 3.0.5 on 2020-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0007_load_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='load',
            name='installation_status',
        ),
        migrations.RemoveField(
            model_name='load',
            name='receipt_status',
        ),
        migrations.AlterField(
            model_name='load',
            name='notification_group',
            field=models.ManyToManyField(blank=True, help_text='The groups to which this load belongs', to='loads.NotificationGroup', verbose_name='Notification Group'),
        ),
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
        migrations.DeleteModel(
            name='InstallationStatus',
        ),
        migrations.DeleteModel(
            name='ReceiptStatus',
        ),
    ]
