# Generated by Django 3.0.5 on 2020-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0008_auto_20200428_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Should this be used as the default value?', verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='load',
            name='sponumber',
            field=models.CharField(blank=True, help_text="the supplier's PO number", max_length=50, null=True, verbose_name='Suppliers PO Number'),
        ),
    ]
