# Generated by Django 3.0.5 on 2020-04-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0009_auto_20200429_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='work_type',
            field=models.ForeignKey(blank=True, default=None, help_text='the type of work to be done with this job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loads.WorkType', verbose_name='Work Type'),
        ),
    ]
