# Generated by Django 3.0.5 on 2020-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0010_auto_20200429_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='work_type',
        ),
        migrations.AddField(
            model_name='load',
            name='do_install',
            field=models.BooleanField(default=False, help_text='if we are to install this', verbose_name='Install?'),
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
