# Generated by Django 3.0.5 on 2020-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0011_auto_20200429_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='sponumber',
            field=models.CharField(blank=True, default='', help_text="the supplier's PO number", max_length=50, verbose_name='Suppliers PO Number'),
            preserve_default=False,
        ),
    ]
