# Generated by Django 3.0.5 on 2020-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0012_auto_20200429_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='do_install',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='if we are to install this', verbose_name='Install?'),
        ),
    ]
