# Generated by Django 3.0.5 on 2020-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0013_auto_20200429_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='do_install',
            field=models.BooleanField(default=False, help_text='if we are to install this', verbose_name='Install?'),
        ),
    ]
