# Generated by Django 3.0.5 on 2020-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0014_auto_20200429_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='if this the "completion" status', verbose_name='Is Complete'),
        ),
    ]
