# Generated by Django 3.0.5 on 2020-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0015_status_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_canceled',
            field=models.BooleanField(default=False, help_text='if this the cancelation status', verbose_name='Is Canceled'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='if this the completion status', verbose_name='Is Complete'),
        ),
    ]
